search:
  image: 
    repository: getmeili/meilisearch
    tag: v1.12
    pullPolicy: IfNotPresent

  environment:
    MEILI_ENV: production

  service:
    type: ClusterIP
    port: 7700

  persistence:
    storageClass: standard
    accessMode: ReadWriteOnce
