name: curio
include:
  - ./docker/supabase.yml

services:
  dev:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    container_name: dev
    volumes:
      - ./src/infra:/workspace
      - ./docker/volumes/search/init.sh:/data/search/init.sh
      - ~/.config/gcloud:/root/.config/gcloud
      - ~/.kube:/root/.kube
      - ./.env.staging:/workspace/.env.staging
      - ./.env.prod:/workspace/.env.prod
      - ~/.aws:/root/.aws
    working_dir: /workspace
    stdin_open: true  # Keep STDIN open
    tty: true  # Allocate a pseudo-TTY
    network_mode: host  # Use host network to resolve internal IP issues
    environment:
      - KUBECONFIG=/root/.kube/config
      - USE_GKE_GCLOUD_AUTH_PLUGIN=True
      - RAILWAY_TOKEN=${RAILWAY_API_KEY}
  app:
    build:
      context: ./
      dockerfile: ./docker/curio-app/Dockerfile
    container_name: curio
    network_mode: host
    working_dir: /app
    command: >
      npm run dev
    volumes:
      - ./.env:/app/.env
      - ./.env:/app/.dev.vars
      - ./.env.staging:/app/.env.staging
      - ./.env.prod:/app/.env.prod
    mem_limit: "6G"
    cpus: 4
    develop:
      watch:
        - action: sync
          path: ./src/app
          target: /app
          ignore:
            - /app/node_modules
        - action: rebuild
          path: ./src/app/package.json
  search:
    image: getmeili/meilisearch:v1.12
    container_name: search
    environment:
      MEILI_ENV: development
      SEARCH_EXTERNAL_ENDPOINT_URL: ${SEARCH_EXTERNAL_ENDPOINT_URL}
      SEARCH_MASTER_API_KEY: ${SEARCH_MASTER_API_KEY}
      SEARCH_APPLICATION_KEY_ID: ${SEARCH_APPLICATION_KEY_ID}
    command:
      - /bin/sh
      - /init.sh
      - start
    ports:
      - 7700:7700
    volumes:
      - ./docker/volumes/search/data:/meili_data
      - ./docker/volumes/search/init.sh:/init.sh
