name: curio
include:
  - ./docker/supabase.yml

services:
  dev:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    container_name: dev
    volumes:
      - ./src/infra:/workspace
      - ./docker/volumes/search/init.sh:/data/search/init.sh
      - ~/.config/gcloud:/root/.config/gcloud
      - ~/.kube:/root/.kube
      - ./.env.staging:/workspace/.env.staging
      - ./.env.prod:/workspace/.env.prod
      - ~/.aws:/root/.aws
    working_dir: /workspace
    stdin_open: true  # Keep STDIN open
    tty: true  # Allocate a pseudo-TTY
    network_mode: host  # Use host network to resolve internal IP issues
    environment:
      - KUBECONFIG=/root/.kube/config
      - USE_GKE_GCLOUD_AUTH_PLUGIN=True
  web:
    build:
      context: ./
      dockerfile: ./docker/curio/Dockerfile
    container_name: curio
    network_mode: host
    working_dir: /app
    command: >
      npm run dev
    depends_on:
      - db
    environment:
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}"
      NEXT_PUBLIC_CURIO_URL: ${NEXT_PUBLIC_CURIO_URL}
      NEXT_PUBLIC_SUPABASE_URL: ${API_EXTERNAL_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
      NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
      NEXT_PUBLIC_POSTHOG_HOST: ${NEXT_PUBLIC_POSTHOG_HOST}
      SEARCH_APPLICATION_API_KEY: ${SEARCH_APPLICATION_API_KEY}
      SEARCH_ENDPOINT_URL: ${SEARCH_ENDPOINT_URL}
      SEARCH_EXTERNAL_ENDPOINT_URL: ${SEARCH_EXTERNAL_ENDPOINT_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      CURIO_APP_SECRET: ${CURIO_APP_SECRET}
      CURIO_EMAIL_DOMAIN: ${CURIO_EMAIL_DOMAIN}
    mem_limit: "6G"
    cpus: 4
    develop:
      watch:
        - action: sync
          path: ./src/web
          target: /app
          ignore:
            - /app/node_modules
        - action: rebuild
          path: ./src/web/package.json
  search:
    image: getmeili/meilisearch:v1.12
    container_name: search
    environment:
      MEILI_ENV: development
      SEARCH_EXTERNAL_ENDPOINT_URL: ${SEARCH_EXTERNAL_ENDPOINT_URL}
      SEARCH_MASTER_API_KEY: ${SEARCH_MASTER_API_KEY}
      SEARCH_APPLICATION_KEY_ID: ${SEARCH_APPLICATION_KEY_ID}
    command:
      - /bin/sh
      - /init.sh
      - start
    ports:
      - 7700:7700
    volumes:
      - ./docker/volumes/search/data:/meili_data
      - ./docker/volumes/search/init.sh:/init.sh
