name: curio
include:
  - ./docker/supabase.yml

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    container_name: curio
    network_mode: host
    working_dir: /app
    command: >
      npm run dev
    depends_on:
      - db
    environment:
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}"
      NEXT_PUBLIC_SUPABASE_URL: ${API_EXTERNAL_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
    mem_limit: "6G"
    cpus: 4
    develop:
      watch:
        - action: sync
          path: ./src/web
          target: /app
          ignore:
            - /app/node_modules
        - action: rebuild
          path: ./src/web/package.json
