name: curio
include:
  - ./docker/supabase.yml

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    container_name: curio
    network_mode: host
    working_dir: /app
    command: >
      npm run dev
    depends_on:
      - db
    environment:
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}"
      NEXT_PUBLIC_SUPABASE_URL: ${API_EXTERNAL_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
      NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
      NEXT_PUBLIC_POSTHOG_HOST: ${NEXT_PUBLIC_POSTHOG_HOST}
      SEARCH_API_KEY: ${SEARCH_APPLICATION_API_KEY}
      SEARCH_ENDPOINT_URL: ${SEARCH_ENDPOINT_URL}
      SEARCH_EXTERNAL_ENDPOINT_URL: ${SEARCH_EXTERNAL_ENDPOINT_URL}
    mem_limit: "6G"
    cpus: 4
    develop:
      watch:
        - action: sync
          path: ./src/web
          target: /app
          ignore:
            - /app/node_modules
        - action: rebuild
          path: ./src/web/package.json
  search:
    image: getmeili/meilisearch:v1.12
    container_name: search
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: ${SEARCH_MASTER_API_KEY}
    command:
      - /bin/sh
      - /init.sh
    ports:
      - 7700:7700
    volumes:
      - ./docker/volumes/search/data:/meili_data
      - ./docker/volumes/search/init.sh:/init.sh
