name: curio
include:
  - ./docker/supabase.yml

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    container_name: curio
    ports:
      - 3000:3000
    working_dir: /app
    command: >
      npm run dev
    depends_on:
      - db
    environment:
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
      SERVER_SUPABASE_URL: http://supabase-kong:8000  # In local dev, this needs to be the address of the Supabase API Docker container.
      NEXT_PUBLIC_SUPABASE_URL: ${API_EXTERNAL_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
    # mem_limit: "6G"
    # cpus: 4
    develop:
      watch:
        - action: sync
          path: ./src/web
          target: /app
          ignore:
            - /app/node_modules
        - action: rebuild
          path: ./src/web/package.json
