apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.cluster_name }}-acme-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: gke-l7-regional-external-managed
  addresses:
  - value: {{ .Values.ip_address }}
    type: NamedAddress
  listeners:
  - name: http
    hostname: {{ .Values.hostname }}
    port: 80
    protocol: HTTP