apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cluster_name }}-search
  namespace: {{ .Release.Namespace }}
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: {{ .Values.search.image.repository }}:{{ .Values.search.image.tag }}
        imagePullPolicy: {{ .Values.search.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.search.service.port }}
        env:
        - name: MEILI_ENV
          value: {{ .Values.search.environment.MEILI_ENV }}
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cluster_name }}-search-master-key
              key: SEARCH_MASTER_API_KEY
        command:
        - /bin/sh
        - /data/search/init.sh
        volumeMounts:
        - name: search-data
          mountPath: /meili_data
      volumes:
      - name: search-data
        persistentVolumeClaim:
          claimName: {{ .Values.cluster_name }}-search-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: curio/node-type
                operator: In
                values:
                - "{{ .Values.primary_node_label }}"
