apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.cluster_name }}-search-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.persistent_volume_disk_size_gb }}Gi
  storageClassName: standard
  selector:
    matchLabels:
      environment: {{ $.Release.Namespace }}