apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.cluster_name }}-search-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - {{ $.Values.search.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $.Values.persistent_volume_disk_size_gb }}Gi
  {{- if $.Values.search.persistence.storageClass }}
  storageClassName: {{ $.Values.search.persistence.storageClass }}
  {{- end }}
  selector:
    matchLabels:
      environment: {{ $.Release.Namespace }}