{{- range $i := until .Values.search.persistence.count }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-search-pvc-%d" $.Release.Name (add $i 1) }}
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - {{ $.Values.search.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $.Values.search.persistence.size }}
  {{- if $.Values.search.persistence.storageClass }}
  storageClassName: {{ $.Values.search.persistence.storageClass }}
  {{- end }}
{{- end }}