apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster_name }}-search-master-key
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SEARCH_MASTER_API_KEY: {{ .Values.searchMasterApiKey }}
