apiVersion: v1
kind: Service
metadata:
  labels:
    app: kong
  name: kong
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    app: kong
