apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest
  name: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
        - args:
            - postgrest
          env:
            - name: PGRST_APP_SETTINGS_JWT_EXP
              value: "${JWT_EXPIRY}"
            - name: PGRST_APP_SETTINGS_JWT_SECRET
              value: "${JWT_SECRET}"
            - name: PGRST_DB_ANON_ROLE
              value: "anon"
            - name: PGRST_DB_SCHEMAS
              value: "${PGRST_DB_SCHEMAS}"
            - name: PGRST_DB_URI
              value: "postgres://authenticator:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
            - name: PGRST_DB_USE_LEGACY_GUCS
              value: "false"
            - name: PGRST_JWT_SECRET
              value: "${JWT_SECRET}"
          image: postgrest/postgrest:v12.2.0
          name: supabase-rest
      restartPolicy: Always
