apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.cluster_name }}-acme-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: gke-l7-regional-external-managed
  addresses:
  - value: {{ .Values.ip_address }}
    type: NamedAddress
  listeners:
  - name: http-staging
    hostname: {{ .Values.staging_hostname }}
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            name: infra
  - name: http-prod
    hostname: {{ .Values.prod_hostname }}
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            name: infra