apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.cluster_name }}-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: gke-l7-regional-external-managed
  addresses:
  - value: {{ .Values.ip_address }}
    type: NamedAddress
  listeners:
  - name: https-staging
    hostname: {{ .Values.staging_hostname }}
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            namespace: staging
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ .Values.cluster_name }}-staging-search-tls
        kind: Secret
  - name: https-prod
    hostname: {{ .Values.prod_hostname }}
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            namespace: prod
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ .Values.cluster_name }}-prod-search-tls
        kind: Secret