name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.9.0"

      - name: Build custom lint rules
        working-directory: ./src/web/eslint-local-rules
        run: npm install && npm run build

      - name: Install dependencies
        working-directory: ./src/web
        run: npm install

      - name: Run lint
        working-directory: ./src/web
        run: npm run lint

      - name: Run build
        working-directory: ./src/web
        run: npm run build

      - name: Run tests
        working-directory: ./src/web
        run: npm run test
