name: Build

on: [push, pull_request]

jobs:
  check-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.9.0"

      - name: Install lint rule
        working-directory: ./src/app/api/eslint-local-rules
        run: npm install && npm run build

      - name: Install dependencies
        working-directory: ./src/app
        run: npm install

      - name: Run lint
        working-directory: ./src/app
        run: npm run lint

      - name: Run tests
        working-directory: ./src/app
        run: npm run test

      - name: Run build (staging)
        working-directory: ./src/app
        run: npm run build -- --mode staging

      - name: Deploy (staging)
        working-directory: ./src/app
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --env staging
          environment: staging

  check-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.9.0"

      - name: WEB - Build custom lint rules
        working-directory: ./src/web/eslint-local-rules
        run: npm install && npm run build

      - name: WEB - Install dependencies
        working-directory: ./src/web
        run: npm install

      - name: WEB - Run lint
        working-directory: ./src/web
        run: npm run lint

      - name: WEB - Run build
        working-directory: ./src/web
        run: npm run build

      - name: WEB - Run tests
        working-directory: ./src/web
        run: npm run test
