name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.9.0"

      - name: [API] Build custom lint rules
        working-directory: ./src/api/eslint-local-rules
        run: npm install && npm run build

      - name: [API] Install dependencies
        working-directory: ./src/api
        run: npm install

      - name: [API] Run lint
        working-directory: ./src/api
        run: npm run lint

      - name: [API] Run build
        working-directory: ./src/api
        run: npm run build

      - name: [API] Run tests
        working-directory: ./src/api
        run: npm run test

      - name: [WEB] Build custom lint rules
        working-directory: ./src/web/eslint-local-rules
        run: npm install && npm run build

      - name: [WEB] Install dependencies
        working-directory: ./src/web
        run: npm install

      - name: [WEB] Run lint
        working-directory: ./src/web
        run: npm run lint

      - name: [WEB] Run build
        working-directory: ./src/web
        run: npm run build

      - name: [WEB] Run tests
        working-directory: ./src/web
        run: npm run test
